// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, createApiKey, updateApiKey, deleteApiKey, validateApiKey,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getSmartModelProfiles, getSmartModelProfile,
  upsertSmartModelProfiles, deleteSmartModelProfiles,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getPricing, updatePricing, resetPricing, resetAllPricing,
  getCloudConnections, getCloudConnectionByProvider, getCloudConnectionById,
  createCloudConnection, deleteCloudConnection,
  getCloudDeployments, getCloudDeploymentById,
  createCloudDeployment, updateCloudDeployment, deleteCloudDeployment,
  exportDb, importDb,
} from "@/lib/db/index";
