
export default {
  id: "gemini",
  priority: 50,
  hasFree: true,
  alias: "gemini",
  display: {
    name: "Gemini",
    icon: "diamond",
    color: "#4285F4",
    textIcon: "GE",
    website: "https://ai.google.dev",
    notice: {
      apiKeyUrl: "https://aistudio.google.com/app/apikey",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  mediaPriority: 1,
  transport: {
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/models",
    format: "gemini",
    clientId: process.env.GOOGLE_OAUTH_CLIENT_ID || "",
    clientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET || "",
    auth: {
      apiKey: {
        header: "x-goog-api-key",
        scheme: "raw",
      },
      oauth: {
        header: "Authorization",
        scheme: "bearer",
      },
    },
  },
    modelOverrides: {
    "gemini-embedding-2-preview": { "kind": "embedding" },
    "gemini-embedding-001": { "kind": "embedding" },
    "text-embedding-005": { "kind": "embedding" },
    "text-embedding-004": { "kind": "embedding" },
    "gemini-3.1-flash-image-preview": { "params": [], "kind": "image" },
    "gemini-3-pro-image-preview": { "params": [], "kind": "image" },
    "gemini-2.5-flash-image": { "params": [], "kind": "image" },
    "gemini-2.5-pro": { "params": ["language", "prompt"], "kind": "stt" },
    "gemini-2.5-flash": { "params": ["language", "prompt"], "kind": "stt" },
    "gemini-2.5-flash-lite": { "params": ["language", "prompt"], "kind": "stt" },
    "gemini-2.0-flash": { "params": ["language", "prompt"], "kind": "stt" },
    "gemini-3.1-flash-tts-preview": { "kind": "tts" },
    "gemini-2.5-flash-preview-tts": { "kind": "tts" },
    "gemini-2.5-pro-preview-tts": { "kind": "tts" },
    "embedding-001": { "dimensions": 768, "kind": "embedding" },
  },
  serviceKinds: ["llm","embedding","image","imageToText","webSearch","tts","stt"],
  ttsConfig: {
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/models",
    authType: "apikey",
    authHeader: "key",
    format: "gemini-tts",
  },
  sttConfig: {
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/models",
    authType: "apikey",
    authHeader: "key",
    format: "gemini-stt",
  },
  embeddingConfig: { baseUrl: "https://generativelanguage.googleapis.com/v1beta/models", authType: "apikey", authHeader: "key" },
  imageConfig: { baseUrl: "https://generativelanguage.googleapis.com/v1beta/models" },
  searchViaChat: {
    defaultModel: "gemini-2.5-flash",
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
    pricingUrl: "https://ai.google.dev/pricing",
    freeTier: "Free tier: 15 RPM, 1M tokens/day on gemini-2.5-flash via AI Studio.",
  },
};
