export default {
  id: "ghe-copilot",
  alias: "ghec",
  uiAlias: "ghec",
  display: {
    name: "GHE Copilot",
    icon: "code",
    color: "#6F42C1",
    website: "https://github.com/enterprise",
    notice: {
      signupUrl: "https://github.com/enterprise",
    },
  },
  category: "oauth",
  hasOAuth: true,
  transport: {
    baseUrl: "https://api.githubcopilot.com/chat/completions",
    format: "openai",
    headers: {
      "copilot-integration-id": "vscode-chat",
      "editor-version": "vscode/1.110.0",
      "editor-plugin-version": "copilot-chat/0.38.0",
      "user-agent": "GitHubCopilotChat/0.38.0",
      "openai-intent": "conversation-panel",
      "x-github-api-version": "2025-04-01",
      "x-vscode-user-agent-library-version": "electron-fetch",
      "X-Initiator": "user",
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    copilot: {
      vscodeVersion: "1.110.0",
      chatVersion: "0.38.0",
      userAgent: "GitHubCopilotChat/0.38.0",
      apiVersion: "2025-04-01",
    },
  },
  models: [
    { id: "copilot/claude-sonnet-4.6", name: "Claude Sonnet 4.6 (Copilot)" },
    { id: "copilot/gpt-5.4", name: "GPT-5.4 (Copilot)" },
    { id: "copilot/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro (Copilot)" },
  ],
  oauth: {
    clientId: "Iv1.b507a08c87ecfe98",
    deviceCodeUrl: "https://github.com/login/device/code",
    tokenUrl: "https://github.com/login/oauth/access_token",
    userInfoUrl: "https://api.github.com/user",
    scopes: "read:user",
    apiVersion: "2022-11-28",
    copilotTokenUrl: "https://api.github.com/copilot_internal/v2/token",
    userAgent: "GitHubCopilotChat/0.26.7",
    editorVersion: "vscode/1.85.0",
    editorPluginVersion: "copilot-chat/0.26.7",
  },
};
