export default {
  id: "kiro",
  priority: 10,
  alias: "kr",
  uiAlias: "kr",
  display: {
    name: "Kiro AI",
    icon: "psychology_alt",
    color: "#FF6B35",
    website: "https://kiro.dev",
    notice: {
      signupUrl: "https://kiro.dev",
    },
    deprecated: true,
    deprecationNotice: "RISK_NOTICE",
  },
  category: "free",
  transport: {
    baseUrl: "https://runtime.us-east-1.kiro.dev/generateAssistantResponse",
    baseUrls: [
      "https://runtime.us-east-1.kiro.dev/generateAssistantResponse",
      "https://codewhisperer.us-east-1.amazonaws.com/generateAssistantResponse",
      "https://q.us-east-1.amazonaws.com/generateAssistantResponse",
    ],
    format: "kiro",
    retry: {
      "429": 0,
    },
    headers: {
      "Content-Type": "application/json",
      Accept: "application/vnd.amazon.eventstream",
      "User-Agent": "AWS-SDK-JS/3.0.0 kiro-ide/1.0.0",
      "X-Amz-User-Agent": "aws-sdk-js/3.0.0 kiro-ide/1.0.0",
    },
    tokenUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/refreshToken",
    authUrl: "https://prod.us-east-1.auth.desktop.kiro.dev",
    usage: {
      cwHost: "https://codewhisperer.us-east-1.amazonaws.com",
      qHost: "https://q.us-east-1.amazonaws.com",
      limitsPath: "/getUsageLimits",
    },
  },
    modelOverrides: {
    "deepseek-3.2": { "strip": ["image", "audio"] },
    "qwen3-coder-next": { "strip": ["image", "audio"] },
    "gpt-5.6-sol": { "rateMultiplier": 2.4, "upstreamModelId": "gpt-5.6-sol" },
    "gpt-5.6-terra": { "rateMultiplier": 1.2, "upstreamModelId": "gpt-5.6-terra" },
    "gpt-5.6-luna": { "rateMultiplier": 0.6, "upstreamModelId": "gpt-5.6-luna" },
    "gpt-5.6-sol-thinking": { "rateMultiplier": 2.4, "upstreamModelId": "gpt-5.6-sol" },
    "gpt-5.6-terra-thinking": { "rateMultiplier": 1.2, "upstreamModelId": "gpt-5.6-terra" },
    "gpt-5.6-luna-thinking": { "rateMultiplier": 0.6, "upstreamModelId": "gpt-5.6-luna" },
    "gpt-5.6-sol-agentic": { "rateMultiplier": 2.4, "upstreamModelId": "gpt-5.6-sol" },
    "gpt-5.6-terra-agentic": { "rateMultiplier": 1.2, "upstreamModelId": "gpt-5.6-terra" },
    "gpt-5.6-luna-agentic": { "rateMultiplier": 0.6, "upstreamModelId": "gpt-5.6-luna" },
    "gpt-5.6-sol-thinking-agentic": { "rateMultiplier": 2.4, "upstreamModelId": "gpt-5.6-sol" },
    "gpt-5.6-terra-thinking-agentic": { "rateMultiplier": 1.2, "upstreamModelId": "gpt-5.6-terra" },
    "gpt-5.6-luna-thinking-agentic": { "rateMultiplier": 0.6, "upstreamModelId": "gpt-5.6-luna" },
  },
  oauth: {
    ssoOidcEndpoint: "https://oidc.us-east-1.amazonaws.com",
    registerClientUrl: "https://oidc.us-east-1.amazonaws.com/client/register",
    deviceAuthUrl: "https://oidc.us-east-1.amazonaws.com/device_authorization",
    tokenUrl: "https://oidc.us-east-1.amazonaws.com/token",
    startUrl: "https://view.awsapps.com/start",
    clientName: "kiro-oauth-client",
    clientType: "public",
    scopes: [
      "codewhisperer:completions",
      "codewhisperer:analysis",
      "codewhisperer:conversations",
    ],
    grantTypes: [
      "urn:ietf:params:oauth:grant-type:device_code",
      "refresh_token",
    ],
    issuerUrl: "https://identitycenter.amazonaws.com/ssoins-722374e8c3c8e6c6",
    socialAuthEndpoint: "https://prod.us-east-1.auth.desktop.kiro.dev",
    socialLoginUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/login",
    socialTokenUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/oauth/token",
    socialRefreshUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/refreshToken",
    authMethods: [
      "builder-id",
      "idc",
      "google",
      "github",
      "import",
    ],
  },
  features: {
    usage: true,
    usageApikey: true,
  },
};
