export default {
  id: "openai",
  priority: 30,
  alias: "openai",
  display: {
    name: "OpenAI",
    icon: "auto_awesome",
    color: "#10A37F",
    textIcon: "OA",
    website: "https://platform.openai.com",
    notice: {
      apiKeyUrl: "https://platform.openai.com/api-keys",
    },
  },
  category: "apikey",
  thinkingConfig: {
    options: [
      "auto",
      "none",
      "low",
      "medium",
      "high",
    ],
    defaultMode: "auto",
  },
  transport: {
    baseUrl: "https://api.openai.com/v1/chat/completions",
    forceStream: true,
  },
    modelOverrides: {
    "text-embedding-3-large": { "kind": "embedding" },
    "text-embedding-3-small": { "kind": "embedding" },
    "text-embedding-ada-002": { "kind": "embedding" },
    "tts-1": { "kind": "tts" },
    "tts-1-hd": { "kind": "tts" },
    "gpt-4o-mini-tts": { "kind": "tts" },
    "whisper-1": { "params": ["language", "response_format", "temperature", "prompt"], "kind": "stt" },
    "gpt-4o-transcribe": { "params": ["language", "response_format", "temperature", "prompt"], "kind": "stt" },
    "gpt-4o-mini-transcribe": { "params": ["language", "response_format", "temperature", "prompt"], "kind": "stt" },
    "gpt-image-1": { "params": ["n", "size", "quality", "response_format"], "kind": "image" },
    "dall-e-3": { "params": ["size", "quality", "style", "response_format"], "kind": "image" },
    "dall-e-2": { "params": ["n", "size", "response_format"], "kind": "image" },
  },
  serviceKinds: ["llm","embedding","tts","stt","image","imageToText","webSearch"],
  ttsConfig: {
    baseUrl: "https://api.openai.com/v1/audio/speech",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
    defaultModel: "gpt-4o-mini-tts",
  },
  sttConfig: {
    baseUrl: "https://api.openai.com/v1/audio/transcriptions",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
  },
  embeddingConfig: { baseUrl: "https://api.openai.com/v1/embeddings", authType: "apikey", authHeader: "bearer" },
  imageConfig: { baseUrl: "https://api.openai.com/v1/images/generations" },
  searchViaChat: { defaultModel: "gpt-4o-mini", pricingUrl: "https://openai.com/api/pricing" },
};
