export default {
  id: "openrouter",
  priority: 10,
  hasFree: true,
  alias: "openrouter",
  display: {
    name: "OpenRouter",
    icon: "router",
    color: "#F97316",
    textIcon: "OR",
    website: "https://openrouter.ai",
    notice: {
      text: "Free tier: 27+ free models, no credit card needed, 200 req/day. After  0 credit: 1,000 req/day.",
      apiKeyUrl: "https://openrouter.ai/settings/keys",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://openrouter.ai/api/v1/chat/completions",
    thinkingFormat: "openai",
    headers: {
      "HTTP-Referer": "https://endpoint-proxy.local",
      "X-Title": "Endpoint Proxy",
    },
  },
    modelOverrides: {
    "openai/text-embedding-3-large": { "kind": "embedding" },
    "openai/text-embedding-3-small": { "kind": "embedding" },
    "openai/text-embedding-ada-002": { "kind": "embedding" },
    "qwen/qwen3-embedding-8b": { "kind": "embedding" },
    "perplexity/pplx-embed-v1-4b": { "kind": "embedding" },
    "perplexity/pplx-embed-v1-0.6b": { "kind": "embedding" },
    "nvidia/llama-nemotron-embed-vl-1b-v2:free": { "kind": "embedding" },
    "openai/gpt-4o-mini-tts": { "kind": "tts" },
    "openai/tts-1-hd": { "kind": "tts" },
    "openai/tts-1": { "kind": "tts" },
    "openai/dall-e-3": { "params": ["size", "quality", "style", "response_format"], "kind": "image" },
    "openai/gpt-image-1": { "params": ["n", "size", "quality", "response_format"], "kind": "image" },
    "google/imagen-3.0-generate-002": { "params": ["n", "size"], "kind": "image" },
    "black-forest-labs/FLUX.1-schnell": { "params": ["n", "size"], "kind": "image" },
  },
  serviceKinds: ["llm","embedding","tts","imageToText"],
  ttsConfig: {
    baseUrl: "https://openrouter.ai/api/v1/chat/completions",
    defaultModel: "openai/gpt-4o-mini-tts",
    headers: {"HTTP-Referer":"https://endpoint-proxy.local","X-Title":"Endpoint Proxy"},
  },
  embeddingConfig: {
    baseUrl: "https://openrouter.ai/api/v1/embeddings",
    authType: "apikey",
    authHeader: "bearer",
    headers: {"HTTP-Referer":"https://endpoint-proxy.local","X-Title":"Endpoint Proxy"},
  },
  imageConfig: {
    baseUrl: "https://openrouter.ai/api/v1/images/generations",
    headers: {"HTTP-Referer":"https://endpoint-proxy.local","X-Title":"Endpoint Proxy"},
  },
  modelsFetcher: { url: "https://openrouter.ai/api/v1/models", type: "openrouter-free" },
  passthroughModels: true,
};
