export default {
  id: "yuanbao-web",
  alias: "yw",
  aliases: ["yuanbao-web"],
  uiAlias: "yw",
  display: {
    name: "Tencent Yuanbao (Free)",
    icon: "auto_awesome",
    color: "#0052D9",
    textIcon: "YW",
    website: "https://yuanbao.tencent.com",
    notice: "Free Tencent Yuanbao (DeepSeek/Hunyuan).",
  },
  category: "webCookie",
  authType: "cookie",
  authHint: "Paste your hy_user and hy_token cookies from yuanbao.tencent.com",
  transport: {
    baseUrl: "https://yuanbao.tencent.com",
    format: "openai",
    authType: "cookie",
  },
  models: [
    { id: "deepseek-v3", name: "DeepSeek V3" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "deepseek-v3-search", name: "DeepSeek V3 (Search)" },
    { id: "deepseek-r1-search", name: "DeepSeek R1 (Search)" },
    { id: "hunyuan", name: "Hunyuan" },
    { id: "hunyuan-t1", name: "Hunyuan T1" },
    { id: "hunyuan-search", name: "Hunyuan (Search)" },
    { id: "hunyuan-t1-search", name: "Hunyuan T1 (Search)" },
  ],
  passthroughModels: true,
};
